version: '3.1'

services:
  ztm_scrapers:
    build: https://github.com/malyyigor34/ztm_scrappers.git
    restart: always
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:343877@mongo:27017
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 343877
    ports:
      - "27017:27017"
    volumes:
      - "/data/ztm_saver/ztm_data:/data/"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 343877
      ME_CONFIG_MONGODB_URL: mongodb://root:343877@mongo:27017